b=imread('coins.png');
a=double(b);
g1=bitget(a,1);
g2=bitget(a,2);
g3=bitget(a,3);
g4=bitget(a,4);
g5=bitget(a,5);
g6=bitget(a,6);
g7=bitget(a,7);
g8=bitget(a,8);
subplot(4,4,[1 8]); imshow(b);
title('original image');
subplot(4,4,9); imshow(g1);
title('bit plane 1 image');
subplot(4,4,10); imshow(g2);
title('bit plane 2 image');
subplot(4,4,11); imshow(g3);
title('bit plane 3 image');
subplot(4,4,12); imshow(g4);
title('bit plane 4 image');
subplot(4,4,13); imshow(g5);
title('bit plane 5 image');
subplot(4,4,14); imshow(g6);
title('bit plane 6 image');
subplot(4,4,15); imshow(g7);
title('bit plane 7 image');
subplot(4,4,16); imshow(g8);
title('bit plane 8 image');